# Generated by Django 5.2.8 on 2025-12-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
